version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
      timezone: Europe/London
    groups:
      github:
        patterns:
          - 'actions/*'

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
      timezone: Europe/London
    ignore:
      - dependency-name: org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom
