[versions]
kotlin = "2.2.21"
serialization = "1.9.0"
coroutines = "1.10.2"
jswrappers = "1.0.0-pre.710"
aws-sdk = "3.922.0"

[libraries]
coroutines-bom = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "coroutines" }
serialization-bom = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-bom", version.ref = "serialization" }
jswrappers-bom = { group = "org.jetbrains.kotlin-wrappers", name = "kotlin-wrappers-bom", version.ref = "jswrappers" }
