name: "Gradle Build"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set up build properties
        run: |
          echo '' > gradle.properties
          echo nodejs.package=ncc >> gradle.properties
      - name: Build
        uses: gradle/gradle-command-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/kotlin' }}
          arguments: build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: build/set-aws-sso-credentials-kotlin-nodejs.zip
